title: The Little Women Musical
logo: docs/assets/download.png
description: A weekend show preformed by talented Ripon High School Students. 
theme: jekyll-theme-minimal
header: Images
image: docs/assets/orange-fruit-pattern-11279546974t3lw.jpg
image: docs/assets/download.png
image: docs/assets/c-domain-images-free-stock-photos-high-quality-resolution-downloads-public-domain-archive-1-1000x667_iazox88bms4wiss0mmdiuy.jpg
header 2: Intrested in the Cast?
<table>
     <tr>
        <td>Name</td>
        <td>Grade</td>
        <td>Role</td>
    </tr>
     <tr>
        <td>Lauren J</td>
        <td>12th</td>
        <td>Amy March</td>
    </tr> 
     <tr>
        <td>Darel P</td>
        <td>10th</td>
        <td>Jo March</td>
     </tr>
     <tr>
        <td>Kate S</td>
        <td>9th</td>
        <td>Beth March</td>
</table>
